.TH RTFM

.SH NAME

RTFM \- Read The Fucking Manual

.SH DESCRIPTION

RTFM stands for "Read The Fucking Manual" and is the "bleeding edge" manual
generator for all systems! It operates using a configuration file called "rtfm.yml",
which is both excrutiatingly slow and very restrictive!

.SH SYNOPSIS

.B rtfm
[\fBoptions\fR]

.SH OPTIONS

.TP
.BR \-h ", " \-\-help
Prints the RTFM help message.

.TP
.BR \-S ", " \-\-Save
Save all of RTFM's tmp files, for example "rtfm.tool".
